openapi: 3.0.0
info:
  title: consuming api data geonames
  description: Corona Virus Kenya Statistics
  version: 0.1.9
servers:
  - url: http://127.0.0.1:5000/
    description: Main server
  - url: http://127.0.0.1:5000/
    description: Testing server at local computer
paths:
  /:
    get:
      summary: Obtain realtime corona virus statistics of kenya.
      description: obtain realtime corona virus statistics of kenya
      responses:
        '200':    # status code
          description: geonames
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
